feTS - Enhancing Type Safety in REST API
the-guild-org/website pull request #1297
Opened 2023-06-25 12:27 UTC by TuvalSimha

2023-06-29 10:21 UTC, beerose reviewed
Maybe it's worth mentioning that the blogpost is specifically about the fets client?

2023-06-29 10:21 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +In this blog post, we will explore a powerful tool called feTS that addresses these problems and provides solutions for more effective REST API development.
consider adding a link to `feTS`

2023-06-29 10:21 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +feTS, which stands for "Framework-Embedded TypeScript," is a robust tool designed specifically for TypeScript projects. It simplifies the development and consumption of REST API while ensuring type s
isn’t feTS fetch + TypeScript?

> TypeScript decorators

it doesn't use decorators from what I know

You can also add that it's fully compatible as long as there's an OpenAPI spec

2023-06-29 10:32 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +feTS, which stands for "Fetch" + "TypeScript" is a robust tool designed specifically for TypeScript projects. It simplifies the development and consumption of REST API while ensuring type safety. By
I'm not sure about the `specifically for TypeScript projects` — you can use the client with a REST API written in any language. Maybe you can mention that feTS **Client** is designed for TypeScript projects?

2023-06-29 10:32 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +- The fetchWebApi function lacks type safety, making it uncertain what data will return from the API.
```suggestion
- The `fetchWebApi` function lacks type safety, making it uncertain what data will return from the API.
```

2023-06-29 10:32 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +- You need to manually specify the parameters of the fetchWebApi function.
```suggestion
- You need to specify the parameters of the `fetchWebApi` function manually.
```

2023-06-29 10:32 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +- The fetchWebApi function allows calling any endpoint, even if it's not supported by the API.
```suggestion
- The `fetchWebApi` function allows calling any endpoint, even if it's not supported by the API.
```

Maybe mention the implications — ie that it's runtime error prone etc

2023-06-29 10:32 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +- The topTracks variable lacks type safety according to the API documentation.
```suggestion
- The `topTracks` variable lacks type safety according to the API documentation.
```

Maybe something simpler like: "We don't know the type of `topTracks`" or that it's `any`

2023-06-29 10:32 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +3. Now, we are ready to use feTS decorators to create a type-safe API client:
```suggestion
3. Now, we are ready to use feTS to create a type-safe API client:
```

2023-06-29 10:32 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +5. In conclusion, we can use the topTracks variable with type safety:
```suggestion
5. In conclusion, we know the type of the `topTracks` variable out-of-the-box.
```

2023-06-29 10:32 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +- Robust Type Safety: feTS eliminates the need for manual type definitions or code generation by inferring types from the OpenAPI specification and JSON Schema. This ensures reliable and type-safe AP
```suggestion
- Robust Type Safety: feTS eliminates the need for manual type definitions or code generation by inferring types from the OpenAPI specification. This ensures reliable and type-safe API interactions.
```

2023-06-29 10:32 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +- OpenAPI Compatibility: By leveraging the OpenAPI specification, feTS seamlessly integrates with various tools and frameworks, providing flexibility and convenience.
It's a bit vague — not sure what it means, maybe an example?

2023-06-29 10:32 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +- Stop be depend on SDK maintainers: feTS allows you to use the API without the need to wait for the SDK maintainers to update the SDK.
```suggestion
- No dependence on SDK maintainers: feTS allows you to use the API without waiting for the SDK maintainers to update the SDK.
```

2023-06-29 10:32 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +- Limited Language Support: feTS built specifically for TypeScript, which may not be suitable for projects utilizing other programming languages.
I'd remove this whole section 😅

2023-06-30 21:26 UTC, Urigo requested changes

2023-06-30 21:26 UTC, Urigo commented on website/pages/blog/type-safe-your-api.mdx
> +- Robust Type Safety: feTS eliminates the need for manual type definitions or code generation by inferring types from the OpenAPI specification. This ensures reliable and type-safe API interactions.
I would maybe even specifically name some clients that don't have type-safety as an examples (axios and maybe others from the announcement blog post), and also Swagger Codegen as an example of codegen one

2023-06-30 21:26 UTC, Urigo commented on website/pages/blog/type-safe-your-api.mdx
> +- No dependence on SDK maintainers: feTS allows you to use the API without waiting for the SDK maintainers to update the SDK.
I would even say that now companies can give up on creating SDKs and they better just offer openapi and direct their users to feTS

2023-06-30 21:26 UTC, Urigo commented on website/pages/blog/type-safe-your-api.mdx
> +- No dependence on SDK maintainers: feTS allows you to use the API without waiting for the SDK maintainers to update the SDK.
I would even mention that you had cases where the provider API has an SDK and you still chose to use feTS

2023-06-30 23:59 UTC, B2o5T commented on website/pages/blog/type-safe-your-api.mdx
> +async function fetchWebApi(endpoint: string, method: string, body: undefined) {
Found a better type for the `body`, `undefined` says nothing

2023-07-10 20:04 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +In our case, we will use the Spotify API, so we can retrieve the OpenAPI document from [here](https://developer.spotify.com/reference/web-api/open-api-schema.yaml). Since this OpenAPI document is in
You can link this — https://api.apis.guru/v2/specs/spotify.com/sonallux/2023.2.27/openapi.json — it's already in the JSON format

2023-07-10 20:29 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +
The fets API changed a bit. `Mutable` is deprecated — you probably need`NormalizeOAS`

2023-07-10 20:41 UTC, beerose requested changes

2023-07-10 20:41 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +const topTracks = await client["/me/top/{type}"].get({
It may also be worth mentioning that this code won't just work — there's a Spotify API token needed

2023-07-11 14:39 UTC, beerose requested changes

2023-07-11 14:39 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +1. Create a Spotify account and retrieve your access token from [here](https://developer.spotify.com/documentation/web-api/reference/get-users-top-artists-and-tracks?type=artists&time_range=short_ter
The link points to the `get-users-top-artists-and-tracks`.

2023-08-17 08:55 UTC, n1ru4l commented on website/pages/blog/type-safe-your-api.mdx
> +link)\[https://github.com/TuvalSimha/feTS-example/blob/main/src/components/teams-crads.tsx] that
```suggestion
link)[https://github.com/TuvalSimha/feTS-example/blob/main/src/components/teams-crads.tsx] that
```

2023-08-17 08:56 UTC, n1ru4l commented on website/pages/blog/type-safe-your-api.mdx
> +Thank you for joining us on this journey through `feTS`. Here's to a future filled with seamless and
I would also add a link here to the fets documentation

2023-08-17 08:57 UTC, n1ru4l commented on website/pages/blog/type-safe-your-api.mdx
> +
Maybe also link to the GitHub repository and full runnable example here?

2023-08-17 10:00 UTC, beerose requested changes

2023-08-17 10:59 UTC, beerose requested changes

2023-08-17 10:59 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +[here](https://the-guild.dev/openapi/`feTS`/client/quick-start#installation).
Maybe let's add instructions here? You're covering some parts below anyway. Also, the link won't work with "`" inside

2023-08-17 10:59 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +[here](https://github.com/TuvalSimha/feTS-example/blob/main/src/feTS/client.ts).
?

2023-08-17 10:59 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +The following code demonstrates how to set up the client with a custom error handling plugin:
That comes a bit out of nowhere. What's the motivation behind adding the error-handling plugin? That could use some explanation and introduction

2023-08-17 10:59 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +power of the `feTS` client we created earlier to fetch data from the SportStats API. The
The first two sentances are more or less the same

2023-08-17 10:59 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +function demonstrates how to use the `feTS` client to make a `GET` request to the
Repeated sentences. You have the same ones above

2023-08-17 10:59 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +Endpoint auto complete: ![Endpoint auto complete](/blog-assets/type-safe-your-api/endpoint.png)
Unnecessary 
```suggestion
![Endpoint auto complete](/blog-assets/type-safe-your-api/endpoint.png)
```

2023-08-17 10:59 UTC, beerose commented on website/pages/blog/type-safe-your-api.mdx
> +[here](https://github.com/TuvalSimha/feTS-example/blob/main/src/feTS/endpoint.ts).
What's the motivation behind these (I saw it also above)?

2023-12-24 09:52 UTC, closed without merging