graphiql v3 blog
the-guild-org/website pull request #1308
Opened 2023-06-30 21:39 UTC by B2o5T

2023-07-03 12:42 UTC, Urigo requested changes

2023-07-03 12:42 UTC, Urigo commented on website/pages/blog/graphiql-3/index.mdx
> +title: GraphiQL 3 Is Here and GraphiQL 4 Is Coming
I would change the title to something that also gives information about the content
maybe like "GraphiQL v3 is here - React 18, better codebase, balblabla, and you can try v4 alpha with Monaco editor!"

2023-07-03 12:42 UTC, Urigo commented on website/pages/blog/graphiql-3/index.mdx
> +description: GraphiQL 3 was released, here is what was changed and what will be in GraphiQL 4.
same here, more information about the content

2023-07-03 12:42 UTC, Urigo commented on website/pages/blog/graphiql-3/index.mdx
> +After months and months, no progress was made, and I was called to join forces and help the
I would make it a bit nicer maybe
Maybe say that you decided to join the team and push all the things on the roadmap

2023-07-03 12:42 UTC, Urigo commented on website/pages/blog/graphiql-3/index.mdx
> +When I started to maintain GraphiQL the first thing first was ESLint improvements, because ESLint
maybe add something like that you need good tools and order for good long term maintenance, which is what The Guild is known for

2023-07-03 12:42 UTC, Urigo commented on website/pages/blog/graphiql-3/index.mdx
> +1. And
I would add here a number of over 150 PRs

2023-07-03 12:42 UTC, Urigo commented on website/pages/blog/graphiql-3/index.mdx
> +<p className="mt-3 text-center italic">Tab reorders made by
I would move that to the previous sentence, something like 

In v3 I've also included the tab reorders feature made by [@mylesmmurphy](https://github.com/mylesmmurphy)
  [#3111](https://github.com/graphql/graphiql/pull/3111):

2023-07-03 12:42 UTC, Urigo commented on website/pages/blog/graphiql-3/index.mdx
> +14 months ago the initial issue was created on the integration `monaco-editor` in GraphiQL.
I think originally the talk about monaco was many years earlier even

2023-07-03 12:42 UTC, Urigo commented on website/pages/blog/graphiql-3/index.mdx
> +<Callout type="warning">
I would phrase it a bit different and less offensive
Maybe you can say that there was some initial work on Jon on a prototype outside of GraphiQL without integration

2023-07-03 12:42 UTC, Urigo commented on website/pages/blog/graphiql-3/index.mdx
> +
here is the current high level roadmap we have for GraphiQL, please comment and let us know what you think is missing:

2024-07-31 08:27 UTC, dimaMachina commented
closing due to obsolescence

2024-07-31 08:27 UTC, closed without merging