blog: GraphQL Protect
the-guild-org/website pull request #1519
Opened 2024-01-30 08:25 UTC by ldebruijn

Publish the GraphQL Protect blogpost on the Guild Website

2024-03-04 18:25 UTC, Urigo requested changes
Great post and very sorry for the late review!!

I think it would be great that when you talk about GraphQL Security you will mention certain solutions like trust documents (persisted queries) and also direct people to trusted places to read about GraphQL Security.
I want to make sure we are not giving people the wrong impression that GraphQL is not secure (which many has currently...)

I would also add inline examples. I know you link to them but usually people would want to see at least a bit of a glimpse before diving in to the docs.

I would also add a call for giving feedback and question about security and your solution, none of us are perfect and its good to tell people they should let you know when we are not

Really excited to get this out this week!

2026-09-03 18:46 UTC, Urigo commented
@ldebruijn do you want to maybe pick this up again?

2026-09-08 17:26 UTC, ldebruijn commented
Hey @Urigo , I completely forgot about this. I think the momentum has passed so I'll pass on it and close the MR. Thank you for reminding me :)

2026-09-08 17:26 UTC, closed without merging

2026-09-08 19:16 UTC, Urigo commented
I'm sorry about that @ldebruijn