brick blog
the-guild-org/website pull request #989
Opened 2022-12-16 01:11 UTC by Josiassejod1

Blog post to introduce Offline GraphQL open source project

2022-12-20 14:26 UTC, Urigo requested changes

2022-12-20 14:26 UTC, Urigo commented on website/pages/blog/offline-graphql-the-easy-parts.mdx
> +title: Offline GraphQL - The easy parts
I would mention Flutter in the title, otherwise people might think it can be used on other ecosystems

2022-12-20 14:26 UTC, Urigo commented on website/pages/blog/offline-graphql-the-easy-parts.mdx
> +title: Offline GraphQL - The easy parts
maybe something like
"Brick - a new, offline first GraphQL Client based on SQLite"?
Or something like that?

2023-01-02 16:23 UTC, Urigo approved these changes

2023-01-03 11:58 UTC, B2o5T commented on website/pages/blog/offline-graphql-the-easy-parts.mdx
> +// eslint-disable-next-line remark-lint-chicago-heading
```suggestion
```

2023-01-25 17:01 UTC, Urigo commented
@Josiassejod1 can you please rebase and update the date?
I'll merge it right after!

2023-01-25 17:17 UTC, B2o5T commented
I will rebase

2023-01-25 17:43 UTC, merged